apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-deployment
  namespace: arju 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
      - name: bookmyshow
        image: arjukumar7/bookmyshow-app:v1
        ports:
        - containerPort: 3000