apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  namespace: arju  
spec:
  type: LoadBalancer
  selector:
    app: bookmyshow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000