global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "jenkins"
    metrics_path: /prometheus
    basic_auth:
      username: "admin"
      password: "8723fe8zg4ba72de12kf7d8494be5h0c37"
    static_configs:
      - targets: ["44.203.132.118:8080"]
